
main(    ){
    int alph;
    alph = 65;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph );
    alph = alph + 1;
    putchar( alph ); 
    alph = alph + 1;
    putchar( alph ); 
    alph = alph + 1;
    putchar( alph ); 
    alph = alph + 1;
    putchar( alph ); 
    alph = alph + 1;
    putchar( alph ); 
    alph = alph + 1;
    putchar( alph ); 
}